import Widgets from '../components/Widgets';
import Head from 'next/head'
import Feed from '../components/Feed';
import Sidebar from "../components/Sidebar";
// import { Inter } from '@next/font/google'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='flex min-h-screen mx-auto'>

      {/* Sidebar */}

      <Sidebar/> 

      {/* Feed */}


      <Feed/>




      {/* Widgets */}
      <Widgets/>

      {/* Modal */}

      </main>


    </div>
  )
}
